### ISSUE TITLE
Zone 252

### ISSUE THREAD

**Issue by sberryman** [nutechsoftware/AlarmDecoder-IoT#47]
I wasn't able to find the information you requested, I tried changing logging mode to Debugging and didn't see anything.

Zone 252 is automatically created when the IoT starts and it toggles between OPEN and CLOSE around 30 seconds after a fault. My guess is `{"last_alpha_message": "COMM. FAILURE", "last_numeric_message": "0fc"}` 

I don't have a phone line connected and for some reason last time I disabled the phone line that setting reset when I disconnected the panel power.

**Comment by sberryman** [comment]
Just observed a strange behavior.

Zone 252 is OPEN until a fault then it closes. Around 30 seconds later it opens again.

However, it also seems that 252 CLOSE on it's own and when 252 is closed, none of the other zones update. The ready state continues to change in MQTT but zero changes to zones happen until I restart the IoT device.

**Comment by f34rdotcom** [comment]
Ahh got it. Ok 252 is "COMM FAILURE". The hex value is 0xfc as you noted in the last message. 

Ok well com failure should just be recorded as a fault but "should" not cause any other issues to other zones.

The fix for the panel will be to clear the PHONE number fields. *41* and *42*

∗41 Primary Phone No.
| | | | | | | | | | | | | | | | | | |
∗∗∗∗42 Second Phone No.
| | | | | | | | | | | | | | | | | | |
Enter up to 20 digits. To clear entries, press ✱41✱ or ✱42✱ respectively.

As for why it stops responding I am not sure but would like to find a way to figure it out. When it is unresponsive on MQTT server does the CLI still function? Commands like 'help' etc?

**Comment by f34rdotcom** [comment]
> Just observed a strange behavior.
> 
> Zone 252 is OPEN until a fault then it closes. Around 30 seconds later it opens again.
> 
> However, it also seems that 252 CLOSE on it's own and when 252 is closed, none of the other zones update. The ready state continues to change in MQTT but zero changes to zones happen until I restart the IoT device.

This makes sense. On "READY" it will clear all faulted zones but then zone 0xfc shows up again even though it is not really a zone and faults when the panel is ready. I need to deal with these special cases better.

**Comment by sberryman** [comment]
I will try and clear the numbers tomorrow. Thanks for help, I'll let you if that fixes the "stuck" zones. 

Yes, everything still functions in the CLI when the zones stop updating. I just plug in the laptop and type "restart". Kind of a pain so hoping that clearing the phone number(s) fixes it.

**Comment by f34rdotcom** [comment]
Needs skip clearing special zones.
https://github.com/nutechsoftware/AlarmDecoder-IoT/blob/ae680569419612b3303c3bd90d16d9b1ad367641/components/alarmdecoder-api/alarmdecoder_api.cpp#L1246

**Comment by sberryman** [comment]
I'm not making this easy by changing many variables at a time here but this is what I did before going to bed last night:

- Added zones 252 and 8 to the `vpart` zone list
- Gave 252 and 8 a fake zone config

I added zone 8 which I don't have setup as I noticed that when 252 was stuck CLOSE, I would fault a zone by opening the door then the panel `last_numeric_message` would go to `008` after clearing the zone fault. I figured that was strange.

Interestingly the system continued to work this morning and didn't get stuck on 252 being closed. 

Another observation, when the zones were stuck I could continue arming and disarming the system via MQTT commands.

**Comment by f34rdotcom** [comment]
Working on this now. Adding a is_system flag to the zone state. As for the glitches let me know if it happens again but so far I have not seen any situations where things locked up. Well to be fair. When I had my AD2IoT in 'ad2term' mode I forget it wont do anything :). That has gotten me several times now. Still working on making that keep processing even in that mode but it will be painful and give little benefit since that command is not often used in production.

**Comment by f34rdotcom** [comment]
This [patch](https://github.com/nutechsoftware/AlarmDecoder-IoT/commit/76dc86beb99fb8ee2a5be8b217336512b4056af0) will add support for system zone types to be flagged.  

Configure 0xfc (252) as "problem" zone types for HA using the 'zone' command as follows. 

`zone 252 {"type": "problem", "alpha": "Failed to call"}`

**Comment by sberryman-bird** [comment]
Great news, I haven't seen any issues once I added zone 252. There does seem to be a slight lag when disabling the alarm (armed home -> disarmed) and triggering a fault (door in my case) a few minutes later where it doesn't publish that fault. It seems like everything goes back to normal after a few faults are triggered which is very strange to me.

Clearly I still haven't cleared the phone numbers.

You mentioned patch, are you going to release a new version or should I just build myself? It is working right now so there isn't a rush on my end.

I appreciate all the work fixing the issues I've come across. Loving the product with all the improvements you've made w/ MQTT!

**Comment by f34rdotcom** [comment]
I plan on adding this an maybe another feature this week. This will give me more time to test this and see if maybe another bug exists. I suspect by adding the zone it fixed the issue so I will review zone events when no zone description exists.

Thanks for the support. I started adding wiki pages for the project. Lots of work still needs to happen but I would appreciate any input.

I need to add remote config support. I have my system connected to a Pi but others have to pull the device down to tweak these settings and play with new features. I am leaning toward adding an FTP server to the device so I can upload a config file. Not many options exist inside of espidf libraries but ftp and tftp servers are an option. I could go through the web interface as well but it will take much more time so I am looking for easy but acceptable. Your input is appreciated. I live in a coders bubble :)

**Comment by f34rdotcom** [comment]
Zones can now be defined in the config file and used as virtual switches for event notifications on on release 1.1+ 
```
[zone 252]
description = {"type": "problem", "alpha": "Failed to call(FC)"}
```
