### ISSUE TITLE
WebUI is always in "Waiting for state"

### ISSUE THREAD

**Issue by kennethxu** [nutechsoftware/AlarmDecoder-IoT#50]
After enabling WebUI and copied the web content to a microSD card, I was able to get the UI to load but it got stuck in "Waiting for state" and cannot be used for anything. BTW, the ser2sock is running and connected to the panel. I can access panel's virtual keypad via Keypad app running on Windows. What could be the problem and how should I debug this?

![Screenshot 2022-02-27 151040](https://user-images.githubusercontent.com/1189766/155898132-64c3269f-080e-42dd-87a8-78b015e9485d.jpg)

**Comment by kennethxu** [comment]
OK, it seems to be having problem with Microsoft Edge browser, my mobile chrome loads into "Ready" state, but Activity and Apps tab don't work at all.

**Comment by f34rdotcom** [comment]
Can you send me the URL your browser is using. It should have some args code= part=
Please confirm these are correct and that the AD2IoT has at least the VPART setting for the slot you are using on the webui are the same. Also the Javascript console on the browser will show any errors and other useful info.

Best
 SM

**Comment by kennethxu** [comment]
Not sure if your answer was towards my original question or the comment about "Activity and Apps" tab does nothing?

The "Waiting for state" issue is browser related so if you test with Microsoft Edge, you'll likely be able to reproduce that.
Browser debug shows that the request going to ws://192.168.0.143/ad2ws failed with status 431. I run it with curl to discover that the error message is: "Header fields are too long for server to interpret". The header that is too long is user-agent.

Anyway the URL is http://ip/app.html?vpartID=0&codeID=0, and I'm still get nothing from Apps or Activity tab.

**Comment by f34rdotcom** [comment]
Yes the Activities and Apps are just a placeholder currently. Sorry I did miss that in your first post. 

Ya I agree I need to have a much thinner intro with links to all the specifics. The instructions are mostly just the raw commands and not a howto or user guide. Will work on it over the next few days and see what you think. As noted a specific user guide for MQTT + HA or ST or WebUI. Also one for WebUI development on some tricks to keep local HTML on your dev box and use the AD2IoT to process all of the commands so the uSD card does not need to be used.

I will work on it. Thanks for the feedback it is much appreciated.

**Comment by f34rdotcom** [comment]
New release ready for testing today. MQTT continues to be improved. Now configuration is easier with config file and setting up smart switches is simple. System already has many pre existing switches configured for discovery. Still more to be done but adding more should be trivial now with these latest changes. I switch variable names and updated http content on this release the default will be part=1 and code=1 to remove all config references to '0' as an index value.

![image](https://user-images.githubusercontent.com/2042644/168883183-cec38a9a-44c9-427c-b9ff-288a1ca299b0.png)

**Comment by f34rdotcom** [comment]
Likely it ran out of sockets. I have updated to the max of 16 sockets. It was set to 10 and I discovered it ran out in some cases and cause network issues. Please try loading the latest release and see if it works better now.

**Comment by f34rdotcom** [comment]
So many changes since this was reported so I will close until / if it shows up again
